# Generated by Django 5.0 on 2023-12-06 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_filmes_filme'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filme',
            table='core_filmes',
        ),
    ]
